#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

SERVICE_NAME=fanctrl
SERVICE_BIN=/usr/bin/fan_ctrl.sh

start_service() {
    procd_open_instance
    procd_set_param command "$SERVICE_BIN"
    procd_set_param respawn 300 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall -9 fan_ctrl.sh
}
