include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-H69kfancontrol
PKG_VERSION:=1.4
PKG_RELEASE:=1
PKG_MAINTAINER:=Your Name <your.email@example.com>
PKG_LICENSE:=MIT

include $(INCLUDE_DIR)/package.mk

define Package/$(PKG_NAME)
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=3. Applications
  TITLE:=H69k Fan Control Interface
  DEPENDS:=+lua +luci-base +luci-compat
  PKGARCH:=all
endef

define Package/$(PKG_NAME)/description
  LuCI web interface for H69k router fan control with temperature monitoring.
endef

define Package/$(PKG_NAME)/install
    # 配置文件
    $(INSTALL_DIR) $(1)/etc/config
    $(INSTALL_CONF) ./files/etc/config/H69k-fancontrol $(1)/etc/config/
    
    # 初始化脚本
    $(INSTALL_DIR) $(1)/etc/init.d
    $(INSTALL_BIN) ./files/etc/init.d/H69k-fancontrol $(1)/etc/init.d/
    $(INSTALL_BIN) ./files/etc/init.d/H69k-fancontrol-init $(1)/etc/init.d/
    
    # LuCI组件
    $(INSTALL_DIR) $(1)/usr/lib/lua/luci/controller
    $(INSTALL_DATA) ./files/usr/lib/lua/luci/controller/H69k-fancontrol.lua $(1)/usr/lib/lua/luci/controller/
    
    $(INSTALL_DIR) $(1)/usr/lib/lua/luci/model/cbi
    $(INSTALL_DATA) ./files/usr/lib/lua/luci/model/cbi/H69k-fancontrol.lua $(1)/usr/lib/lua/luci/model/cbi/
    
    $(INSTALL_DIR) $(1)/usr/lib/lua/luci/view/H69k-fancontrol
    $(INSTALL_DATA) ./files/usr/lib/lua/luci/view/H69k-fancontrol/status.htm $(1)/usr/lib/lua/luci/view/H69k-fancontrol/
    
    # 语言文件
    $(INSTALL_DIR) $(1)/usr/lib/lua/luci/i18n
    $(INSTALL_DATA) ./po/zh_Hans/H69k-fancontrol.po $(1)/usr/lib/lua/luci/i18n/H69k-fancontrol.zh-cn.po
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
