include $(TOPDIR)/rules.mk

PKG_NAME:=h69kfan
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/h69kfan
    SECTION:=utils
    CATEGORY:=Utilities
    TITLE:=Auto-Enabled PWM Fan Control
    DEPENDS:=+kmod-hwmon-core +kmod-hwmon-pwm-fan
    PKGARCH:=all
endef

define Package/h69kfan/description
 Hardcoded PWM fan control service with auto-enablement
endef

define Build/Configure
endef

define Build/Compile
endef

define Package/h69kfan/install
    $(INSTALL_DIR) $(1)/usr/sbin
    $(INSTALL_BIN) ./files/h69kfan.sh $(1)/usr/sbin/
    
    $(INSTALL_DIR) $(1)/etc/init.d
    $(INSTALL_BIN) ./files/h69kfan.init $(1)/etc/init.d/h69kfan
    
    $(INSTALL_DIR) $(1)/etc/uci-defaults
    $(INSTALL_BIN) ./files/99-enable-h69kfan $(1)/etc/uci-defaults/
endef

define Package/h69kfan/prerm
#!/bin/sh
if [ "$${IPKG_INSTROOT}" = "1" ]; then exit 0; fi [ "$$1" = "remove" ] && {
    /etc/init.d/h69kfan stop
    /etc/init.d/h69kfan disable
}
exit 0
endef

$(eval $(call BuildPackage,h69kfan))
