#!/bin/sh
CONFIG_FILE="/etc/config/h69kfan"
PWM_CTRL="/sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1"
TEMP_SENSOR="/sys/class/thermal/thermal_zone0/temp"

read_config() {
    uci -q show "$CONFIG_FILE" | sed "s/'//g" | awk -F= '
        /start_temp/ {st=$2} 
        /full_temp/  {ft=$2}
        /min_pwm/    {min=$2} 
        /max_pwm/    {max=$2}
        /interval/   {iv=$2}
        END {
            printf "start_temp=%d\nfull_temp=%d\nmin_pwm=%d\nmax_pwm=%d\ninterval=%d\n", 
                st?st:35, ft?ft:45, min?min:100, max?max:255, iv?iv:20
        }'
}

get_temp() {
    temp_raw=$(cat $TEMP_SENSOR 2>/dev/null | tr -cd '0-9')
    [ -z "$temp_raw" ] && exit 100
    echo $((temp_raw / 1000))
}

calc_pwm() {
    eval $(read_config)
    if [ $1 -le $start_temp ]; then
        echo $min_pwm
    elif [ $1 -ge $full_temp ]; then
        echo $max_pwm
    else
        pwm_range=$((max_pwm - min_pwm))
        temp_range=$((full_temp - start_temp))
        echo $(( min_pwm + ($1 - start_temp) * pwm_range / temp_range ))
    fi
}

trap 'echo $min_pwm > $PWM_CTRL; exit' EXIT

eval $(read_config)
while :; do
    temp=$(get_temp) || temp=$full_temp
    pwm=$(calc_pwm $temp)
    
    [ $pwm -lt $min_pwm ] && pwm=$min_pwm
    [ $pwm -gt $max_pwm ] && pwm=$max_pwm
    echo $pwm > $PWM_CTRL
    
    sleep $interval
done
