#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

boot() {
    # 设置初始转速为30
    [ -f /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1 ] && {
        echo 30 > /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1
        chmod 666 /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1
    }
}

start() {
    # 确保启动时设置
    [ -f /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1 ] && {
        echo 30 > /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1
    }
}
