#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    config_load fanh69k
    config_get enabled global enabled 1

    [ "$enabled" = "1" ] && {
        procd_open_instance
        procd_set_param command /usr/sbin/fanh69k
        procd_close_instance
    }
}

stop_service() {
    killall fanh69k
    echo 0 > /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1
}
