#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PWM_CTRL="/sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1"

start_service() {
    [ -w "$PWM_CTRL" ] || {
        logger -t fanh69k "ERROR: PWM device $PWM_CTRL not writable"
        exit 1
    }
    procd_open_instance
    procd_set_param command /usr/sbin/fanh69k
    procd_close_instance
}

stop_service() {
    killall fanh69k
    echo 0 > "$PWM_CTRL"
}
